// Code generated by protoc-gen-go.
// source: sheket_service.proto
// DO NOT EDIT!

/*
Package sheketproto is a generated protocol buffer package.

It is generated from these files:
	sheket_service.proto

It has these top-level messages:
	EmptyRequest
	EmptyResponse
	SheketAuth
	CompanyID
	CompanyAuth
	SingupRequest
	SignupResponse
	SyncCompanyRequest
	NewCompanyRequest
	Company
	CompanyList
	EditUserNameRequest
	AddEmployeeRequest
	AddEmployeeResponse
	IssuePaymentRequest
	IssuePaymentResponse
	VerifyPaymentRequest
	VerifyPaymentResponse
	EditCompanyRequest
	Item
	Category
	Branch
	Employee
	BranchItem
	BranchCategory
	EntityRequest
	EntityResponse
	Transaction
	TransactionRequest
	TransactionResponse
*/
package sheketproto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type EntityRequest_Action int32

const (
	EntityRequest_CREATE EntityRequest_Action = 0
	EntityRequest_UPDATE EntityRequest_Action = 1
	EntityRequest_DELETE EntityRequest_Action = 2
)

var EntityRequest_Action_name = map[int32]string{
	0: "CREATE",
	1: "UPDATE",
	2: "DELETE",
}
var EntityRequest_Action_value = map[string]int32{
	"CREATE": 0,
	"UPDATE": 1,
	"DELETE": 2,
}

func (x EntityRequest_Action) String() string {
	return proto.EnumName(EntityRequest_Action_name, int32(x))
}
func (EntityRequest_Action) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{25, 0} }

type EntityResponse_SyncState int32

const (
	// EXIST is the default state(so it can be left out).
	// If you deleted it, set it to REMOVED.
	EntityResponse_EXIST   EntityResponse_SyncState = 0
	EntityResponse_REMOVED EntityResponse_SyncState = 1
)

var EntityResponse_SyncState_name = map[int32]string{
	0: "EXIST",
	1: "REMOVED",
}
var EntityResponse_SyncState_value = map[string]int32{
	"EXIST":   0,
	"REMOVED": 1,
}

func (x EntityResponse_SyncState) String() string {
	return proto.EnumName(EntityResponse_SyncState_name, int32(x))
}
func (EntityResponse_SyncState) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{26, 0} }

// *
// Common Messages
type EmptyRequest struct {
}

func (m *EmptyRequest) Reset()                    { *m = EmptyRequest{} }
func (m *EmptyRequest) String() string            { return proto.CompactTextString(m) }
func (*EmptyRequest) ProtoMessage()               {}
func (*EmptyRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type EmptyResponse struct {
}

func (m *EmptyResponse) Reset()                    { *m = EmptyResponse{} }
func (m *EmptyResponse) String() string            { return proto.CompactTextString(m) }
func (*EmptyResponse) ProtoMessage()               {}
func (*EmptyResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

// Requests that require the user to be authenticated need to embed this.
type SheketAuth struct {
	LoginCookie string `protobuf:"bytes,1,opt,name=login_cookie,json=loginCookie" json:"login_cookie,omitempty"`
}

func (m *SheketAuth) Reset()                    { *m = SheketAuth{} }
func (m *SheketAuth) String() string            { return proto.CompactTextString(m) }
func (*SheketAuth) ProtoMessage()               {}
func (*SheketAuth) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type CompanyID struct {
	CompanyId int32 `protobuf:"varint,1,opt,name=company_id,json=companyId" json:"company_id,omitempty"`
}

func (m *CompanyID) Reset()                    { *m = CompanyID{} }
func (m *CompanyID) String() string            { return proto.CompactTextString(m) }
func (*CompanyID) ProtoMessage()               {}
func (*CompanyID) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type CompanyAuth struct {
	SheketAuth *SheketAuth `protobuf:"bytes,1,opt,name=sheketAuth" json:"sheketAuth,omitempty"`
	CompanyId  *CompanyID  `protobuf:"bytes,2,opt,name=company_id,json=companyId" json:"company_id,omitempty"`
}

func (m *CompanyAuth) Reset()                    { *m = CompanyAuth{} }
func (m *CompanyAuth) String() string            { return proto.CompactTextString(m) }
func (*CompanyAuth) ProtoMessage()               {}
func (*CompanyAuth) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *CompanyAuth) GetSheketAuth() *SheketAuth {
	if m != nil {
		return m.SheketAuth
	}
	return nil
}

func (m *CompanyAuth) GetCompanyId() *CompanyID {
	if m != nil {
		return m.CompanyId
	}
	return nil
}

type SingupRequest struct {
	Token string `protobuf:"bytes,1,opt,name=token" json:"token,omitempty"`
}

func (m *SingupRequest) Reset()                    { *m = SingupRequest{} }
func (m *SingupRequest) String() string            { return proto.CompactTextString(m) }
func (*SingupRequest) ProtoMessage()               {}
func (*SingupRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

type SignupResponse struct {
	Username    string `protobuf:"bytes,1,opt,name=username" json:"username,omitempty"`
	UserId      int32  `protobuf:"varint,2,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	LoginCookie string `protobuf:"bytes,3,opt,name=login_cookie,json=loginCookie" json:"login_cookie,omitempty"`
}

func (m *SignupResponse) Reset()                    { *m = SignupResponse{} }
func (m *SignupResponse) String() string            { return proto.CompactTextString(m) }
func (*SignupResponse) ProtoMessage()               {}
func (*SignupResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

type SyncCompanyRequest struct {
	Auth          *SheketAuth `protobuf:"bytes,1,opt,name=auth" json:"auth,omitempty"`
	UserRev       int32       `protobuf:"varint,2,opt,name=user_rev,json=userRev" json:"user_rev,omitempty"`
	DeviceId      string      `protobuf:"bytes,3,opt,name=device_id,json=deviceId" json:"device_id,omitempty"`
	LocalUserTime string      `protobuf:"bytes,4,opt,name=local_user_time,json=localUserTime" json:"local_user_time,omitempty"`
}

func (m *SyncCompanyRequest) Reset()                    { *m = SyncCompanyRequest{} }
func (m *SyncCompanyRequest) String() string            { return proto.CompactTextString(m) }
func (*SyncCompanyRequest) ProtoMessage()               {}
func (*SyncCompanyRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *SyncCompanyRequest) GetAuth() *SheketAuth {
	if m != nil {
		return m.Auth
	}
	return nil
}

type NewCompanyRequest struct {
	Auth          *SheketAuth `protobuf:"bytes,1,opt,name=auth" json:"auth,omitempty"`
	CompanyName   string      `protobuf:"bytes,2,opt,name=company_name,json=companyName" json:"company_name,omitempty"`
	DeviceId      string      `protobuf:"bytes,3,opt,name=device_id,json=deviceId" json:"device_id,omitempty"`
	LocalUserTime string      `protobuf:"bytes,4,opt,name=local_user_time,json=localUserTime" json:"local_user_time,omitempty"`
}

func (m *NewCompanyRequest) Reset()                    { *m = NewCompanyRequest{} }
func (m *NewCompanyRequest) String() string            { return proto.CompactTextString(m) }
func (*NewCompanyRequest) ProtoMessage()               {}
func (*NewCompanyRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *NewCompanyRequest) GetAuth() *SheketAuth {
	if m != nil {
		return m.Auth
	}
	return nil
}

type Company struct {
	CompanyId     int32  `protobuf:"varint,1,opt,name=company_id,json=companyId" json:"company_id,omitempty"`
	CompanyName   string `protobuf:"bytes,2,opt,name=company_name,json=companyName" json:"company_name,omitempty"`
	Permission    string `protobuf:"bytes,3,opt,name=permission" json:"permission,omitempty"`
	SignedLicense string `protobuf:"bytes,4,opt,name=signed_license,json=signedLicense" json:"signed_license,omitempty"`
	// being able to generate payment_id at the server end gives us flexibilty
	PaymentId string `protobuf:"bytes,5,opt,name=payment_id,json=paymentId" json:"payment_id,omitempty"`
}

func (m *Company) Reset()                    { *m = Company{} }
func (m *Company) String() string            { return proto.CompactTextString(m) }
func (*Company) ProtoMessage()               {}
func (*Company) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

type CompanyList struct {
	Companies []*Company `protobuf:"bytes,1,rep,name=companies" json:"companies,omitempty"`
}

func (m *CompanyList) Reset()                    { *m = CompanyList{} }
func (m *CompanyList) String() string            { return proto.CompactTextString(m) }
func (*CompanyList) ProtoMessage()               {}
func (*CompanyList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *CompanyList) GetCompanies() []*Company {
	if m != nil {
		return m.Companies
	}
	return nil
}

type EditUserNameRequest struct {
	Auth    *SheketAuth `protobuf:"bytes,1,opt,name=auth" json:"auth,omitempty"`
	NewName string      `protobuf:"bytes,2,opt,name=new_name,json=newName" json:"new_name,omitempty"`
}

func (m *EditUserNameRequest) Reset()                    { *m = EditUserNameRequest{} }
func (m *EditUserNameRequest) String() string            { return proto.CompactTextString(m) }
func (*EditUserNameRequest) ProtoMessage()               {}
func (*EditUserNameRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *EditUserNameRequest) GetAuth() *SheketAuth {
	if m != nil {
		return m.Auth
	}
	return nil
}

type AddEmployeeRequest struct {
	CompanyAuth *CompanyAuth `protobuf:"bytes,1,opt,name=companyAuth" json:"companyAuth,omitempty"`
	EmployeeId  int32        `protobuf:"varint,2,opt,name=employee_id,json=employeeId" json:"employee_id,omitempty"`
	Permission  string       `protobuf:"bytes,3,opt,name=permission" json:"permission,omitempty"`
}

func (m *AddEmployeeRequest) Reset()                    { *m = AddEmployeeRequest{} }
func (m *AddEmployeeRequest) String() string            { return proto.CompactTextString(m) }
func (*AddEmployeeRequest) ProtoMessage()               {}
func (*AddEmployeeRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *AddEmployeeRequest) GetCompanyAuth() *CompanyAuth {
	if m != nil {
		return m.CompanyAuth
	}
	return nil
}

type AddEmployeeResponse struct {
	EmployeeId   int32  `protobuf:"varint,1,opt,name=employee_id,json=employeeId" json:"employee_id,omitempty"`
	EmployeeName string `protobuf:"bytes,2,opt,name=employee_name,json=employeeName" json:"employee_name,omitempty"`
}

func (m *AddEmployeeResponse) Reset()                    { *m = AddEmployeeResponse{} }
func (m *AddEmployeeResponse) String() string            { return proto.CompactTextString(m) }
func (*AddEmployeeResponse) ProtoMessage()               {}
func (*AddEmployeeResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

type IssuePaymentRequest struct {
	SheketAuth    *SheketAuth `protobuf:"bytes,1,opt,name=sheketAuth" json:"sheketAuth,omitempty"`
	CompanyId     int32       `protobuf:"varint,2,opt,name=company_id,json=companyId" json:"company_id,omitempty"`
	ContractType  int32       `protobuf:"varint,3,opt,name=contract_type,json=contractType" json:"contract_type,omitempty"`
	DurationDays  int32       `protobuf:"varint,4,opt,name=duration_days,json=durationDays" json:"duration_days,omitempty"`
	EmployeeLimit int32       `protobuf:"zigzag32,5,opt,name=employee_limit,json=employeeLimit" json:"employee_limit,omitempty"`
	BranchLimit   int32       `protobuf:"zigzag32,6,opt,name=branch_limit,json=branchLimit" json:"branch_limit,omitempty"`
	ItemLimit     int32       `protobuf:"zigzag32,7,opt,name=item_limit,json=itemLimit" json:"item_limit,omitempty"`
}

func (m *IssuePaymentRequest) Reset()                    { *m = IssuePaymentRequest{} }
func (m *IssuePaymentRequest) String() string            { return proto.CompactTextString(m) }
func (*IssuePaymentRequest) ProtoMessage()               {}
func (*IssuePaymentRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *IssuePaymentRequest) GetSheketAuth() *SheketAuth {
	if m != nil {
		return m.SheketAuth
	}
	return nil
}

type IssuePaymentResponse struct {
	IssuedCompanyId    int32  `protobuf:"varint,1,opt,name=issued_company_id,json=issuedCompanyId" json:"issued_company_id,omitempty"`
	PaymentDescription string `protobuf:"bytes,2,opt,name=payment_description,json=paymentDescription" json:"payment_description,omitempty"`
}

func (m *IssuePaymentResponse) Reset()                    { *m = IssuePaymentResponse{} }
func (m *IssuePaymentResponse) String() string            { return proto.CompactTextString(m) }
func (*IssuePaymentResponse) ProtoMessage()               {}
func (*IssuePaymentResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

type VerifyPaymentRequest struct {
	CompanyAuth   *CompanyAuth `protobuf:"bytes,1,opt,name=companyAuth" json:"companyAuth,omitempty"`
	DeviceId      string       `protobuf:"bytes,2,opt,name=device_id,json=deviceId" json:"device_id,omitempty"`
	LocalUserTime string       `protobuf:"bytes,3,opt,name=local_user_time,json=localUserTime" json:"local_user_time,omitempty"`
}

func (m *VerifyPaymentRequest) Reset()                    { *m = VerifyPaymentRequest{} }
func (m *VerifyPaymentRequest) String() string            { return proto.CompactTextString(m) }
func (*VerifyPaymentRequest) ProtoMessage()               {}
func (*VerifyPaymentRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func (m *VerifyPaymentRequest) GetCompanyAuth() *CompanyAuth {
	if m != nil {
		return m.CompanyAuth
	}
	return nil
}

type VerifyPaymentResponse struct {
	SignedLicense string `protobuf:"bytes,1,opt,name=signed_license,json=signedLicense" json:"signed_license,omitempty"`
}

func (m *VerifyPaymentResponse) Reset()                    { *m = VerifyPaymentResponse{} }
func (m *VerifyPaymentResponse) String() string            { return proto.CompactTextString(m) }
func (*VerifyPaymentResponse) ProtoMessage()               {}
func (*VerifyPaymentResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

type EditCompanyRequest struct {
	CompanyAuth *CompanyAuth `protobuf:"bytes,1,opt,name=companyAuth" json:"companyAuth,omitempty"`
	NewName     string       `protobuf:"bytes,2,opt,name=new_name,json=newName" json:"new_name,omitempty"`
}

func (m *EditCompanyRequest) Reset()                    { *m = EditCompanyRequest{} }
func (m *EditCompanyRequest) String() string            { return proto.CompactTextString(m) }
func (*EditCompanyRequest) ProtoMessage()               {}
func (*EditCompanyRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{18} }

func (m *EditCompanyRequest) GetCompanyAuth() *CompanyAuth {
	if m != nil {
		return m.CompanyAuth
	}
	return nil
}

type Item struct {
	ItemId            int32   `protobuf:"zigzag32,1,opt,name=item_id,json=itemId" json:"item_id,omitempty"`
	Name              string  `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Code              string  `protobuf:"bytes,3,opt,name=code" json:"code,omitempty"`
	UUID              string  `protobuf:"bytes,4,opt,name=UUID,json=uUID" json:"UUID,omitempty"`
	StatusFlag        int32   `protobuf:"varint,5,opt,name=status_flag,json=statusFlag" json:"status_flag,omitempty"`
	CategoryId        int32   `protobuf:"zigzag32,6,opt,name=category_id,json=categoryId" json:"category_id,omitempty"`
	UnitOfMeasurement int32   `protobuf:"varint,7,opt,name=unit_of_measurement,json=unitOfMeasurement" json:"unit_of_measurement,omitempty"`
	HasDerivedUnit    bool    `protobuf:"varint,8,opt,name=has_derived_unit,json=hasDerivedUnit" json:"has_derived_unit,omitempty"`
	DerivedName       string  `protobuf:"bytes,9,opt,name=derived_name,json=derivedName" json:"derived_name,omitempty"`
	DerivedFactor     float64 `protobuf:"fixed64,10,opt,name=derived_factor,json=derivedFactor" json:"derived_factor,omitempty"`
}

func (m *Item) Reset()                    { *m = Item{} }
func (m *Item) String() string            { return proto.CompactTextString(m) }
func (*Item) ProtoMessage()               {}
func (*Item) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{19} }

type Category struct {
	CategoryId int32  `protobuf:"zigzag32,1,opt,name=category_id,json=categoryId" json:"category_id,omitempty"`
	Name       string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	ParentId   int32  `protobuf:"zigzag32,3,opt,name=parent_id,json=parentId" json:"parent_id,omitempty"`
	UUID       string `protobuf:"bytes,4,opt,name=UUID,json=uUID" json:"UUID,omitempty"`
	StatusFlag int32  `protobuf:"varint,5,opt,name=status_flag,json=statusFlag" json:"status_flag,omitempty"`
}

func (m *Category) Reset()                    { *m = Category{} }
func (m *Category) String() string            { return proto.CompactTextString(m) }
func (*Category) ProtoMessage()               {}
func (*Category) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{20} }

type Branch struct {
	BranchId   int32  `protobuf:"zigzag32,1,opt,name=branch_id,json=branchId" json:"branch_id,omitempty"`
	Name       string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	UUID       string `protobuf:"bytes,3,opt,name=UUID,json=uUID" json:"UUID,omitempty"`
	StatusFlag int32  `protobuf:"varint,4,opt,name=status_flag,json=statusFlag" json:"status_flag,omitempty"`
}

func (m *Branch) Reset()                    { *m = Branch{} }
func (m *Branch) String() string            { return proto.CompactTextString(m) }
func (*Branch) ProtoMessage()               {}
func (*Branch) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{21} }

type Employee struct {
	EmployeeId int32  `protobuf:"varint,1,opt,name=employee_id,json=employeeId" json:"employee_id,omitempty"`
	Name       string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Permission string `protobuf:"bytes,3,opt,name=permission" json:"permission,omitempty"`
}

func (m *Employee) Reset()                    { *m = Employee{} }
func (m *Employee) String() string            { return proto.CompactTextString(m) }
func (*Employee) ProtoMessage()               {}
func (*Employee) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{22} }

type BranchItem struct {
	BranchId      int32   `protobuf:"zigzag32,1,opt,name=branch_id,json=branchId" json:"branch_id,omitempty"`
	ItemId        int32   `protobuf:"zigzag32,2,opt,name=item_id,json=itemId" json:"item_id,omitempty"`
	Quantity      float64 `protobuf:"fixed64,3,opt,name=quantity" json:"quantity,omitempty"`
	ShelfLocation string  `protobuf:"bytes,4,opt,name=shelf_location,json=shelfLocation" json:"shelf_location,omitempty"`
}

func (m *BranchItem) Reset()                    { *m = BranchItem{} }
func (m *BranchItem) String() string            { return proto.CompactTextString(m) }
func (*BranchItem) ProtoMessage()               {}
func (*BranchItem) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{23} }

type BranchCategory struct {
	BranchId   int32 `protobuf:"zigzag32,1,opt,name=branch_id,json=branchId" json:"branch_id,omitempty"`
	CategoryId int32 `protobuf:"zigzag32,2,opt,name=category_id,json=categoryId" json:"category_id,omitempty"`
}

func (m *BranchCategory) Reset()                    { *m = BranchCategory{} }
func (m *BranchCategory) String() string            { return proto.CompactTextString(m) }
func (*BranchCategory) ProtoMessage()               {}
func (*BranchCategory) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{24} }

type EntityRequest struct {
	Items                []*EntityRequest_RequestItem           `protobuf:"bytes,1,rep,name=items" json:"items,omitempty"`
	Categories           []*EntityRequest_RequestCategory       `protobuf:"bytes,2,rep,name=categories" json:"categories,omitempty"`
	Branches             []*EntityRequest_RequestBranch         `protobuf:"bytes,3,rep,name=branches" json:"branches,omitempty"`
	Employees            []*EntityRequest_RequestEmployee       `protobuf:"bytes,4,rep,name=employees" json:"employees,omitempty"`
	BranchItems          []*EntityRequest_RequestBranchItem     `protobuf:"bytes,5,rep,name=branchItems" json:"branchItems,omitempty"`
	BranchCategories     []*EntityRequest_RequestBranchCategory `protobuf:"bytes,6,rep,name=branchCategories" json:"branchCategories,omitempty"`
	CompanyAuth          *CompanyAuth                           `protobuf:"bytes,20,opt,name=companyAuth" json:"companyAuth,omitempty"`
	OldCategoryRev       int32                                  `protobuf:"varint,21,opt,name=old_category_rev,json=oldCategoryRev" json:"old_category_rev,omitempty"`
	OldItemRev           int32                                  `protobuf:"varint,22,opt,name=old_item_rev,json=oldItemRev" json:"old_item_rev,omitempty"`
	OldBranchRev         int32                                  `protobuf:"varint,23,opt,name=old_branch_rev,json=oldBranchRev" json:"old_branch_rev,omitempty"`
	OldBranchItemRev     int32                                  `protobuf:"varint,24,opt,name=old_branch_item_rev,json=oldBranchItemRev" json:"old_branch_item_rev,omitempty"`
	OldMemberRev         int32                                  `protobuf:"varint,25,opt,name=old_member_rev,json=oldMemberRev" json:"old_member_rev,omitempty"`
	OldBranchCategoryRev int32                                  `protobuf:"varint,26,opt,name=old_branch_category_rev,json=oldBranchCategoryRev" json:"old_branch_category_rev,omitempty"`
}

func (m *EntityRequest) Reset()                    { *m = EntityRequest{} }
func (m *EntityRequest) String() string            { return proto.CompactTextString(m) }
func (*EntityRequest) ProtoMessage()               {}
func (*EntityRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{25} }

func (m *EntityRequest) GetItems() []*EntityRequest_RequestItem {
	if m != nil {
		return m.Items
	}
	return nil
}

func (m *EntityRequest) GetCategories() []*EntityRequest_RequestCategory {
	if m != nil {
		return m.Categories
	}
	return nil
}

func (m *EntityRequest) GetBranches() []*EntityRequest_RequestBranch {
	if m != nil {
		return m.Branches
	}
	return nil
}

func (m *EntityRequest) GetEmployees() []*EntityRequest_RequestEmployee {
	if m != nil {
		return m.Employees
	}
	return nil
}

func (m *EntityRequest) GetBranchItems() []*EntityRequest_RequestBranchItem {
	if m != nil {
		return m.BranchItems
	}
	return nil
}

func (m *EntityRequest) GetBranchCategories() []*EntityRequest_RequestBranchCategory {
	if m != nil {
		return m.BranchCategories
	}
	return nil
}

func (m *EntityRequest) GetCompanyAuth() *CompanyAuth {
	if m != nil {
		return m.CompanyAuth
	}
	return nil
}

type EntityRequest_RequestItem struct {
	Item   *Item                `protobuf:"bytes,1,opt,name=item" json:"item,omitempty"`
	Action EntityRequest_Action `protobuf:"varint,2,opt,name=action,enum=sheketproto.EntityRequest_Action" json:"action,omitempty"`
}

func (m *EntityRequest_RequestItem) Reset()                    { *m = EntityRequest_RequestItem{} }
func (m *EntityRequest_RequestItem) String() string            { return proto.CompactTextString(m) }
func (*EntityRequest_RequestItem) ProtoMessage()               {}
func (*EntityRequest_RequestItem) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{25, 0} }

func (m *EntityRequest_RequestItem) GetItem() *Item {
	if m != nil {
		return m.Item
	}
	return nil
}

type EntityRequest_RequestCategory struct {
	Category *Category            `protobuf:"bytes,1,opt,name=category" json:"category,omitempty"`
	Action   EntityRequest_Action `protobuf:"varint,2,opt,name=action,enum=sheketproto.EntityRequest_Action" json:"action,omitempty"`
}

func (m *EntityRequest_RequestCategory) Reset()         { *m = EntityRequest_RequestCategory{} }
func (m *EntityRequest_RequestCategory) String() string { return proto.CompactTextString(m) }
func (*EntityRequest_RequestCategory) ProtoMessage()    {}
func (*EntityRequest_RequestCategory) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{25, 1}
}

func (m *EntityRequest_RequestCategory) GetCategory() *Category {
	if m != nil {
		return m.Category
	}
	return nil
}

type EntityRequest_RequestBranch struct {
	Branch *Branch              `protobuf:"bytes,1,opt,name=branch" json:"branch,omitempty"`
	Action EntityRequest_Action `protobuf:"varint,2,opt,name=action,enum=sheketproto.EntityRequest_Action" json:"action,omitempty"`
}

func (m *EntityRequest_RequestBranch) Reset()                    { *m = EntityRequest_RequestBranch{} }
func (m *EntityRequest_RequestBranch) String() string            { return proto.CompactTextString(m) }
func (*EntityRequest_RequestBranch) ProtoMessage()               {}
func (*EntityRequest_RequestBranch) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{25, 2} }

func (m *EntityRequest_RequestBranch) GetBranch() *Branch {
	if m != nil {
		return m.Branch
	}
	return nil
}

type EntityRequest_RequestEmployee struct {
	Action   EntityRequest_Action `protobuf:"varint,1,opt,name=action,enum=sheketproto.EntityRequest_Action" json:"action,omitempty"`
	Employee *Employee            `protobuf:"bytes,2,opt,name=employee" json:"employee,omitempty"`
}

func (m *EntityRequest_RequestEmployee) Reset()         { *m = EntityRequest_RequestEmployee{} }
func (m *EntityRequest_RequestEmployee) String() string { return proto.CompactTextString(m) }
func (*EntityRequest_RequestEmployee) ProtoMessage()    {}
func (*EntityRequest_RequestEmployee) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{25, 3}
}

func (m *EntityRequest_RequestEmployee) GetEmployee() *Employee {
	if m != nil {
		return m.Employee
	}
	return nil
}

type EntityRequest_RequestBranchItem struct {
	Action     EntityRequest_Action `protobuf:"varint,1,opt,name=action,enum=sheketproto.EntityRequest_Action" json:"action,omitempty"`
	BranchItem *BranchItem          `protobuf:"bytes,2,opt,name=branchItem" json:"branchItem,omitempty"`
}

func (m *EntityRequest_RequestBranchItem) Reset()         { *m = EntityRequest_RequestBranchItem{} }
func (m *EntityRequest_RequestBranchItem) String() string { return proto.CompactTextString(m) }
func (*EntityRequest_RequestBranchItem) ProtoMessage()    {}
func (*EntityRequest_RequestBranchItem) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{25, 4}
}

func (m *EntityRequest_RequestBranchItem) GetBranchItem() *BranchItem {
	if m != nil {
		return m.BranchItem
	}
	return nil
}

type EntityRequest_RequestBranchCategory struct {
	Action         EntityRequest_Action `protobuf:"varint,1,opt,name=action,enum=sheketproto.EntityRequest_Action" json:"action,omitempty"`
	BranchCategory *BranchCategory      `protobuf:"bytes,2,opt,name=branchCategory" json:"branchCategory,omitempty"`
}

func (m *EntityRequest_RequestBranchCategory) Reset()         { *m = EntityRequest_RequestBranchCategory{} }
func (m *EntityRequest_RequestBranchCategory) String() string { return proto.CompactTextString(m) }
func (*EntityRequest_RequestBranchCategory) ProtoMessage()    {}
func (*EntityRequest_RequestBranchCategory) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{25, 5}
}

func (m *EntityRequest_RequestBranchCategory) GetBranchCategory() *BranchCategory {
	if m != nil {
		return m.BranchCategory
	}
	return nil
}

type EntityResponse struct {
	UpdatedItemIds       []*EntityResponse_UpdatedId          `protobuf:"bytes,1,rep,name=updated_item_ids,json=updatedItemIds" json:"updated_item_ids,omitempty"`
	UpdatedBranchIds     []*EntityResponse_UpdatedId          `protobuf:"bytes,2,rep,name=updated_branch_ids,json=updatedBranchIds" json:"updated_branch_ids,omitempty"`
	UpdatedCategoryIds   []*EntityResponse_UpdatedId          `protobuf:"bytes,3,rep,name=updated_category_ids,json=updatedCategoryIds" json:"updated_category_ids,omitempty"`
	Items                []*EntityResponse_SyncItem           `protobuf:"bytes,4,rep,name=items" json:"items,omitempty"`
	Categories           []*EntityResponse_SyncCategory       `protobuf:"bytes,5,rep,name=categories" json:"categories,omitempty"`
	Branches             []*EntityResponse_SyncBranch         `protobuf:"bytes,6,rep,name=branches" json:"branches,omitempty"`
	Employees            []*EntityResponse_SyncEmployee       `protobuf:"bytes,7,rep,name=employees" json:"employees,omitempty"`
	BranchCategories     []*EntityResponse_SyncBranchCategory `protobuf:"bytes,8,rep,name=branchCategories" json:"branchCategories,omitempty"`
	NewCategoryRev       int32                                `protobuf:"varint,20,opt,name=new_category_rev,json=newCategoryRev" json:"new_category_rev,omitempty"`
	NewItemRev           int32                                `protobuf:"varint,21,opt,name=new_item_rev,json=newItemRev" json:"new_item_rev,omitempty"`
	NewBranchRev         int32                                `protobuf:"varint,22,opt,name=new_branch_rev,json=newBranchRev" json:"new_branch_rev,omitempty"`
	NewBranchItemRev     int32                                `protobuf:"varint,23,opt,name=new_branch_item_rev,json=newBranchItemRev" json:"new_branch_item_rev,omitempty"`
	NewMemberRev         int32                                `protobuf:"varint,24,opt,name=new_member_rev,json=newMemberRev" json:"new_member_rev,omitempty"`
	NewBranchCategoryRev int32                                `protobuf:"varint,25,opt,name=new_branch_category_rev,json=newBranchCategoryRev" json:"new_branch_category_rev,omitempty"`
}

func (m *EntityResponse) Reset()                    { *m = EntityResponse{} }
func (m *EntityResponse) String() string            { return proto.CompactTextString(m) }
func (*EntityResponse) ProtoMessage()               {}
func (*EntityResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{26} }

func (m *EntityResponse) GetUpdatedItemIds() []*EntityResponse_UpdatedId {
	if m != nil {
		return m.UpdatedItemIds
	}
	return nil
}

func (m *EntityResponse) GetUpdatedBranchIds() []*EntityResponse_UpdatedId {
	if m != nil {
		return m.UpdatedBranchIds
	}
	return nil
}

func (m *EntityResponse) GetUpdatedCategoryIds() []*EntityResponse_UpdatedId {
	if m != nil {
		return m.UpdatedCategoryIds
	}
	return nil
}

func (m *EntityResponse) GetItems() []*EntityResponse_SyncItem {
	if m != nil {
		return m.Items
	}
	return nil
}

func (m *EntityResponse) GetCategories() []*EntityResponse_SyncCategory {
	if m != nil {
		return m.Categories
	}
	return nil
}

func (m *EntityResponse) GetBranches() []*EntityResponse_SyncBranch {
	if m != nil {
		return m.Branches
	}
	return nil
}

func (m *EntityResponse) GetEmployees() []*EntityResponse_SyncEmployee {
	if m != nil {
		return m.Employees
	}
	return nil
}

func (m *EntityResponse) GetBranchCategories() []*EntityResponse_SyncBranchCategory {
	if m != nil {
		return m.BranchCategories
	}
	return nil
}

type EntityResponse_SyncItem struct {
	Item  *Item                    `protobuf:"bytes,1,opt,name=item" json:"item,omitempty"`
	State EntityResponse_SyncState `protobuf:"varint,2,opt,name=state,enum=sheketproto.EntityResponse_SyncState" json:"state,omitempty"`
}

func (m *EntityResponse_SyncItem) Reset()                    { *m = EntityResponse_SyncItem{} }
func (m *EntityResponse_SyncItem) String() string            { return proto.CompactTextString(m) }
func (*EntityResponse_SyncItem) ProtoMessage()               {}
func (*EntityResponse_SyncItem) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{26, 0} }

func (m *EntityResponse_SyncItem) GetItem() *Item {
	if m != nil {
		return m.Item
	}
	return nil
}

type EntityResponse_SyncCategory struct {
	Category *Category                `protobuf:"bytes,1,opt,name=category" json:"category,omitempty"`
	State    EntityResponse_SyncState `protobuf:"varint,2,opt,name=state,enum=sheketproto.EntityResponse_SyncState" json:"state,omitempty"`
}

func (m *EntityResponse_SyncCategory) Reset()                    { *m = EntityResponse_SyncCategory{} }
func (m *EntityResponse_SyncCategory) String() string            { return proto.CompactTextString(m) }
func (*EntityResponse_SyncCategory) ProtoMessage()               {}
func (*EntityResponse_SyncCategory) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{26, 1} }

func (m *EntityResponse_SyncCategory) GetCategory() *Category {
	if m != nil {
		return m.Category
	}
	return nil
}

type EntityResponse_SyncBranch struct {
	Branch *Branch                  `protobuf:"bytes,1,opt,name=branch" json:"branch,omitempty"`
	State  EntityResponse_SyncState `protobuf:"varint,2,opt,name=state,enum=sheketproto.EntityResponse_SyncState" json:"state,omitempty"`
}

func (m *EntityResponse_SyncBranch) Reset()                    { *m = EntityResponse_SyncBranch{} }
func (m *EntityResponse_SyncBranch) String() string            { return proto.CompactTextString(m) }
func (*EntityResponse_SyncBranch) ProtoMessage()               {}
func (*EntityResponse_SyncBranch) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{26, 2} }

func (m *EntityResponse_SyncBranch) GetBranch() *Branch {
	if m != nil {
		return m.Branch
	}
	return nil
}

type EntityResponse_SyncEmployee struct {
	Employee *Employee                `protobuf:"bytes,1,opt,name=employee" json:"employee,omitempty"`
	State    EntityResponse_SyncState `protobuf:"varint,2,opt,name=state,enum=sheketproto.EntityResponse_SyncState" json:"state,omitempty"`
}

func (m *EntityResponse_SyncEmployee) Reset()                    { *m = EntityResponse_SyncEmployee{} }
func (m *EntityResponse_SyncEmployee) String() string            { return proto.CompactTextString(m) }
func (*EntityResponse_SyncEmployee) ProtoMessage()               {}
func (*EntityResponse_SyncEmployee) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{26, 3} }

func (m *EntityResponse_SyncEmployee) GetEmployee() *Employee {
	if m != nil {
		return m.Employee
	}
	return nil
}

type EntityResponse_SyncBranchCategory struct {
	BranchCategory *BranchCategory          `protobuf:"bytes,1,opt,name=branchCategory" json:"branchCategory,omitempty"`
	State          EntityResponse_SyncState `protobuf:"varint,2,opt,name=state,enum=sheketproto.EntityResponse_SyncState" json:"state,omitempty"`
}

func (m *EntityResponse_SyncBranchCategory) Reset()         { *m = EntityResponse_SyncBranchCategory{} }
func (m *EntityResponse_SyncBranchCategory) String() string { return proto.CompactTextString(m) }
func (*EntityResponse_SyncBranchCategory) ProtoMessage()    {}
func (*EntityResponse_SyncBranchCategory) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{26, 4}
}

func (m *EntityResponse_SyncBranchCategory) GetBranchCategory() *BranchCategory {
	if m != nil {
		return m.BranchCategory
	}
	return nil
}

type EntityResponse_UpdatedId struct {
	// old_id is signed because it can be -ve
	OldId int32 `protobuf:"zigzag32,1,opt,name=old_id,json=oldId" json:"old_id,omitempty"`
	// new_id can't be -ve, so it is not signed
	NewId int32 `protobuf:"varint,2,opt,name=new_id,json=newId" json:"new_id,omitempty"`
}

func (m *EntityResponse_UpdatedId) Reset()                    { *m = EntityResponse_UpdatedId{} }
func (m *EntityResponse_UpdatedId) String() string            { return proto.CompactTextString(m) }
func (*EntityResponse_UpdatedId) ProtoMessage()               {}
func (*EntityResponse_UpdatedId) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{26, 5} }

type Transaction struct {
	TransactionItems []*Transaction_TransItem `protobuf:"bytes,1,rep,name=transactionItems" json:"transactionItems,omitempty"`
	TransId          int64                    `protobuf:"zigzag64,2,opt,name=trans_id,json=transId" json:"trans_id,omitempty"`
	BranchId         int32                    `protobuf:"zigzag32,3,opt,name=branch_id,json=branchId" json:"branch_id,omitempty"`
	DateTime         int64                    `protobuf:"varint,4,opt,name=date_time,json=dateTime" json:"date_time,omitempty"`
	TransNote        string                   `protobuf:"bytes,5,opt,name=trans_note,json=transNote" json:"trans_note,omitempty"`
	UUID             string                   `protobuf:"bytes,6,opt,name=UUID,json=uUID" json:"UUID,omitempty"`
}

func (m *Transaction) Reset()                    { *m = Transaction{} }
func (m *Transaction) String() string            { return proto.CompactTextString(m) }
func (*Transaction) ProtoMessage()               {}
func (*Transaction) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{27} }

func (m *Transaction) GetTransactionItems() []*Transaction_TransItem {
	if m != nil {
		return m.TransactionItems
	}
	return nil
}

type Transaction_TransItem struct {
	ItemId        int32   `protobuf:"varint,2,opt,name=item_id,json=itemId" json:"item_id,omitempty"`
	TransType     int32   `protobuf:"varint,1,opt,name=trans_type,json=transType" json:"trans_type,omitempty"`
	Quantity      float64 `protobuf:"fixed64,3,opt,name=quantity" json:"quantity,omitempty"`
	OtherBranchId int32   `protobuf:"varint,4,opt,name=other_branch_id,json=otherBranchId" json:"other_branch_id,omitempty"`
	ItemNote      string  `protobuf:"bytes,5,opt,name=item_note,json=itemNote" json:"item_note,omitempty"`
}

func (m *Transaction_TransItem) Reset()                    { *m = Transaction_TransItem{} }
func (m *Transaction_TransItem) String() string            { return proto.CompactTextString(m) }
func (*Transaction_TransItem) ProtoMessage()               {}
func (*Transaction_TransItem) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{27, 0} }

type TransactionRequest struct {
	Transactions     []*Transaction `protobuf:"bytes,1,rep,name=transactions" json:"transactions,omitempty"`
	CompanyAuth      *CompanyAuth   `protobuf:"bytes,2,opt,name=companyAuth" json:"companyAuth,omitempty"`
	OldBranchItemRev int64          `protobuf:"varint,3,opt,name=old_branch_item_rev,json=oldBranchItemRev" json:"old_branch_item_rev,omitempty"`
	OldTransRev      int64          `protobuf:"varint,4,opt,name=old_trans_rev,json=oldTransRev" json:"old_trans_rev,omitempty"`
}

func (m *TransactionRequest) Reset()                    { *m = TransactionRequest{} }
func (m *TransactionRequest) String() string            { return proto.CompactTextString(m) }
func (*TransactionRequest) ProtoMessage()               {}
func (*TransactionRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{28} }

func (m *TransactionRequest) GetTransactions() []*Transaction {
	if m != nil {
		return m.Transactions
	}
	return nil
}

func (m *TransactionRequest) GetCompanyAuth() *CompanyAuth {
	if m != nil {
		return m.CompanyAuth
	}
	return nil
}

type TransactionResponse struct {
	Transactions          []*TransactionResponse_SyncTransaction `protobuf:"bytes,1,rep,name=transactions" json:"transactions,omitempty"`
	BranchItems           []*TransactionResponse_SyncBranchItem  `protobuf:"bytes,2,rep,name=branchItems" json:"branchItems,omitempty"`
	UpdatedTransactionIds []*TransactionResponse_UpdatedTransId  `protobuf:"bytes,3,rep,name=updated_transaction_ids,json=updatedTransactionIds" json:"updated_transaction_ids,omitempty"`
	NewBranchItemRev      int64                                  `protobuf:"varint,4,opt,name=new_branch_item_rev,json=newBranchItemRev" json:"new_branch_item_rev,omitempty"`
	NewTransRev           int64                                  `protobuf:"varint,5,opt,name=new_trans_rev,json=newTransRev" json:"new_trans_rev,omitempty"`
}

func (m *TransactionResponse) Reset()                    { *m = TransactionResponse{} }
func (m *TransactionResponse) String() string            { return proto.CompactTextString(m) }
func (*TransactionResponse) ProtoMessage()               {}
func (*TransactionResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{29} }

func (m *TransactionResponse) GetTransactions() []*TransactionResponse_SyncTransaction {
	if m != nil {
		return m.Transactions
	}
	return nil
}

func (m *TransactionResponse) GetBranchItems() []*TransactionResponse_SyncBranchItem {
	if m != nil {
		return m.BranchItems
	}
	return nil
}

func (m *TransactionResponse) GetUpdatedTransactionIds() []*TransactionResponse_UpdatedTransId {
	if m != nil {
		return m.UpdatedTransactionIds
	}
	return nil
}

type TransactionResponse_SyncTransaction struct {
	Transaction *Transaction `protobuf:"bytes,1,opt,name=transaction" json:"transaction,omitempty"`
	UserId      int32        `protobuf:"varint,2,opt,name=user_id,json=userId" json:"user_id,omitempty"`
}

func (m *TransactionResponse_SyncTransaction) Reset()         { *m = TransactionResponse_SyncTransaction{} }
func (m *TransactionResponse_SyncTransaction) String() string { return proto.CompactTextString(m) }
func (*TransactionResponse_SyncTransaction) ProtoMessage()    {}
func (*TransactionResponse_SyncTransaction) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{29, 0}
}

func (m *TransactionResponse_SyncTransaction) GetTransaction() *Transaction {
	if m != nil {
		return m.Transaction
	}
	return nil
}

type TransactionResponse_SyncBranchItem struct {
	BranchItem *BranchItem              `protobuf:"bytes,1,opt,name=branchItem" json:"branchItem,omitempty"`
	State      EntityResponse_SyncState `protobuf:"varint,2,opt,name=state,enum=sheketproto.EntityResponse_SyncState" json:"state,omitempty"`
}

func (m *TransactionResponse_SyncBranchItem) Reset()         { *m = TransactionResponse_SyncBranchItem{} }
func (m *TransactionResponse_SyncBranchItem) String() string { return proto.CompactTextString(m) }
func (*TransactionResponse_SyncBranchItem) ProtoMessage()    {}
func (*TransactionResponse_SyncBranchItem) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{29, 1}
}

func (m *TransactionResponse_SyncBranchItem) GetBranchItem() *BranchItem {
	if m != nil {
		return m.BranchItem
	}
	return nil
}

type TransactionResponse_UpdatedTransId struct {
	OldId int64 `protobuf:"zigzag64,1,opt,name=old_id,json=oldId" json:"old_id,omitempty"`
	NewId int64 `protobuf:"varint,2,opt,name=new_id,json=newId" json:"new_id,omitempty"`
}

func (m *TransactionResponse_UpdatedTransId) Reset()         { *m = TransactionResponse_UpdatedTransId{} }
func (m *TransactionResponse_UpdatedTransId) String() string { return proto.CompactTextString(m) }
func (*TransactionResponse_UpdatedTransId) ProtoMessage()    {}
func (*TransactionResponse_UpdatedTransId) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{29, 2}
}

func init() {
	proto.RegisterType((*EmptyRequest)(nil), "sheketproto.EmptyRequest")
	proto.RegisterType((*EmptyResponse)(nil), "sheketproto.EmptyResponse")
	proto.RegisterType((*SheketAuth)(nil), "sheketproto.SheketAuth")
	proto.RegisterType((*CompanyID)(nil), "sheketproto.CompanyID")
	proto.RegisterType((*CompanyAuth)(nil), "sheketproto.CompanyAuth")
	proto.RegisterType((*SingupRequest)(nil), "sheketproto.SingupRequest")
	proto.RegisterType((*SignupResponse)(nil), "sheketproto.SignupResponse")
	proto.RegisterType((*SyncCompanyRequest)(nil), "sheketproto.SyncCompanyRequest")
	proto.RegisterType((*NewCompanyRequest)(nil), "sheketproto.NewCompanyRequest")
	proto.RegisterType((*Company)(nil), "sheketproto.Company")
	proto.RegisterType((*CompanyList)(nil), "sheketproto.CompanyList")
	proto.RegisterType((*EditUserNameRequest)(nil), "sheketproto.EditUserNameRequest")
	proto.RegisterType((*AddEmployeeRequest)(nil), "sheketproto.AddEmployeeRequest")
	proto.RegisterType((*AddEmployeeResponse)(nil), "sheketproto.AddEmployeeResponse")
	proto.RegisterType((*IssuePaymentRequest)(nil), "sheketproto.IssuePaymentRequest")
	proto.RegisterType((*IssuePaymentResponse)(nil), "sheketproto.IssuePaymentResponse")
	proto.RegisterType((*VerifyPaymentRequest)(nil), "sheketproto.VerifyPaymentRequest")
	proto.RegisterType((*VerifyPaymentResponse)(nil), "sheketproto.VerifyPaymentResponse")
	proto.RegisterType((*EditCompanyRequest)(nil), "sheketproto.EditCompanyRequest")
	proto.RegisterType((*Item)(nil), "sheketproto.Item")
	proto.RegisterType((*Category)(nil), "sheketproto.Category")
	proto.RegisterType((*Branch)(nil), "sheketproto.Branch")
	proto.RegisterType((*Employee)(nil), "sheketproto.Employee")
	proto.RegisterType((*BranchItem)(nil), "sheketproto.BranchItem")
	proto.RegisterType((*BranchCategory)(nil), "sheketproto.BranchCategory")
	proto.RegisterType((*EntityRequest)(nil), "sheketproto.EntityRequest")
	proto.RegisterType((*EntityRequest_RequestItem)(nil), "sheketproto.EntityRequest.RequestItem")
	proto.RegisterType((*EntityRequest_RequestCategory)(nil), "sheketproto.EntityRequest.RequestCategory")
	proto.RegisterType((*EntityRequest_RequestBranch)(nil), "sheketproto.EntityRequest.RequestBranch")
	proto.RegisterType((*EntityRequest_RequestEmployee)(nil), "sheketproto.EntityRequest.RequestEmployee")
	proto.RegisterType((*EntityRequest_RequestBranchItem)(nil), "sheketproto.EntityRequest.RequestBranchItem")
	proto.RegisterType((*EntityRequest_RequestBranchCategory)(nil), "sheketproto.EntityRequest.RequestBranchCategory")
	proto.RegisterType((*EntityResponse)(nil), "sheketproto.EntityResponse")
	proto.RegisterType((*EntityResponse_SyncItem)(nil), "sheketproto.EntityResponse.SyncItem")
	proto.RegisterType((*EntityResponse_SyncCategory)(nil), "sheketproto.EntityResponse.SyncCategory")
	proto.RegisterType((*EntityResponse_SyncBranch)(nil), "sheketproto.EntityResponse.SyncBranch")
	proto.RegisterType((*EntityResponse_SyncEmployee)(nil), "sheketproto.EntityResponse.SyncEmployee")
	proto.RegisterType((*EntityResponse_SyncBranchCategory)(nil), "sheketproto.EntityResponse.SyncBranchCategory")
	proto.RegisterType((*EntityResponse_UpdatedId)(nil), "sheketproto.EntityResponse.UpdatedId")
	proto.RegisterType((*Transaction)(nil), "sheketproto.Transaction")
	proto.RegisterType((*Transaction_TransItem)(nil), "sheketproto.Transaction.TransItem")
	proto.RegisterType((*TransactionRequest)(nil), "sheketproto.TransactionRequest")
	proto.RegisterType((*TransactionResponse)(nil), "sheketproto.TransactionResponse")
	proto.RegisterType((*TransactionResponse_SyncTransaction)(nil), "sheketproto.TransactionResponse.SyncTransaction")
	proto.RegisterType((*TransactionResponse_SyncBranchItem)(nil), "sheketproto.TransactionResponse.SyncBranchItem")
	proto.RegisterType((*TransactionResponse_UpdatedTransId)(nil), "sheketproto.TransactionResponse.UpdatedTransId")
	proto.RegisterEnum("sheketproto.EntityRequest_Action", EntityRequest_Action_name, EntityRequest_Action_value)
	proto.RegisterEnum("sheketproto.EntityResponse_SyncState", EntityResponse_SyncState_name, EntityResponse_SyncState_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for SheketService service

type SheketServiceClient interface {
	UserSignup(ctx context.Context, in *SingupRequest, opts ...grpc.CallOption) (*SignupResponse, error)
	SyncCompanies(ctx context.Context, in *SyncCompanyRequest, opts ...grpc.CallOption) (*CompanyList, error)
	EditUserName(ctx context.Context, in *EditUserNameRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
	CreateCompany(ctx context.Context, in *NewCompanyRequest, opts ...grpc.CallOption) (*Company, error)
	EditCompany(ctx context.Context, in *EditCompanyRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
	AddEmployee(ctx context.Context, in *AddEmployeeRequest, opts ...grpc.CallOption) (*AddEmployeeResponse, error)
	SyncEntity(ctx context.Context, in *EntityRequest, opts ...grpc.CallOption) (*EntityResponse, error)
	SyncTransaction(ctx context.Context, in *TransactionRequest, opts ...grpc.CallOption) (*TransactionResponse, error)
	IssuePayment(ctx context.Context, in *IssuePaymentRequest, opts ...grpc.CallOption) (*IssuePaymentResponse, error)
	VerifyPayment(ctx context.Context, in *VerifyPaymentRequest, opts ...grpc.CallOption) (*VerifyPaymentResponse, error)
}

type sheketServiceClient struct {
	cc *grpc.ClientConn
}

func NewSheketServiceClient(cc *grpc.ClientConn) SheketServiceClient {
	return &sheketServiceClient{cc}
}

func (c *sheketServiceClient) UserSignup(ctx context.Context, in *SingupRequest, opts ...grpc.CallOption) (*SignupResponse, error) {
	out := new(SignupResponse)
	err := grpc.Invoke(ctx, "/sheketproto.SheketService/UserSignup", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sheketServiceClient) SyncCompanies(ctx context.Context, in *SyncCompanyRequest, opts ...grpc.CallOption) (*CompanyList, error) {
	out := new(CompanyList)
	err := grpc.Invoke(ctx, "/sheketproto.SheketService/SyncCompanies", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sheketServiceClient) EditUserName(ctx context.Context, in *EditUserNameRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	out := new(EmptyResponse)
	err := grpc.Invoke(ctx, "/sheketproto.SheketService/EditUserName", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sheketServiceClient) CreateCompany(ctx context.Context, in *NewCompanyRequest, opts ...grpc.CallOption) (*Company, error) {
	out := new(Company)
	err := grpc.Invoke(ctx, "/sheketproto.SheketService/CreateCompany", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sheketServiceClient) EditCompany(ctx context.Context, in *EditCompanyRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	out := new(EmptyResponse)
	err := grpc.Invoke(ctx, "/sheketproto.SheketService/EditCompany", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sheketServiceClient) AddEmployee(ctx context.Context, in *AddEmployeeRequest, opts ...grpc.CallOption) (*AddEmployeeResponse, error) {
	out := new(AddEmployeeResponse)
	err := grpc.Invoke(ctx, "/sheketproto.SheketService/AddEmployee", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sheketServiceClient) SyncEntity(ctx context.Context, in *EntityRequest, opts ...grpc.CallOption) (*EntityResponse, error) {
	out := new(EntityResponse)
	err := grpc.Invoke(ctx, "/sheketproto.SheketService/SyncEntity", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sheketServiceClient) SyncTransaction(ctx context.Context, in *TransactionRequest, opts ...grpc.CallOption) (*TransactionResponse, error) {
	out := new(TransactionResponse)
	err := grpc.Invoke(ctx, "/sheketproto.SheketService/SyncTransaction", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sheketServiceClient) IssuePayment(ctx context.Context, in *IssuePaymentRequest, opts ...grpc.CallOption) (*IssuePaymentResponse, error) {
	out := new(IssuePaymentResponse)
	err := grpc.Invoke(ctx, "/sheketproto.SheketService/IssuePayment", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sheketServiceClient) VerifyPayment(ctx context.Context, in *VerifyPaymentRequest, opts ...grpc.CallOption) (*VerifyPaymentResponse, error) {
	out := new(VerifyPaymentResponse)
	err := grpc.Invoke(ctx, "/sheketproto.SheketService/VerifyPayment", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for SheketService service

type SheketServiceServer interface {
	UserSignup(context.Context, *SingupRequest) (*SignupResponse, error)
	SyncCompanies(context.Context, *SyncCompanyRequest) (*CompanyList, error)
	EditUserName(context.Context, *EditUserNameRequest) (*EmptyResponse, error)
	CreateCompany(context.Context, *NewCompanyRequest) (*Company, error)
	EditCompany(context.Context, *EditCompanyRequest) (*EmptyResponse, error)
	AddEmployee(context.Context, *AddEmployeeRequest) (*AddEmployeeResponse, error)
	SyncEntity(context.Context, *EntityRequest) (*EntityResponse, error)
	SyncTransaction(context.Context, *TransactionRequest) (*TransactionResponse, error)
	IssuePayment(context.Context, *IssuePaymentRequest) (*IssuePaymentResponse, error)
	VerifyPayment(context.Context, *VerifyPaymentRequest) (*VerifyPaymentResponse, error)
}

func RegisterSheketServiceServer(s *grpc.Server, srv SheketServiceServer) {
	s.RegisterService(&_SheketService_serviceDesc, srv)
}

func _SheketService_UserSignup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SingupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SheketServiceServer).UserSignup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sheketproto.SheketService/UserSignup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SheketServiceServer).UserSignup(ctx, req.(*SingupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SheketService_SyncCompanies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncCompanyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SheketServiceServer).SyncCompanies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sheketproto.SheketService/SyncCompanies",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SheketServiceServer).SyncCompanies(ctx, req.(*SyncCompanyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SheketService_EditUserName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EditUserNameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SheketServiceServer).EditUserName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sheketproto.SheketService/EditUserName",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SheketServiceServer).EditUserName(ctx, req.(*EditUserNameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SheketService_CreateCompany_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewCompanyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SheketServiceServer).CreateCompany(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sheketproto.SheketService/CreateCompany",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SheketServiceServer).CreateCompany(ctx, req.(*NewCompanyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SheketService_EditCompany_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EditCompanyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SheketServiceServer).EditCompany(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sheketproto.SheketService/EditCompany",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SheketServiceServer).EditCompany(ctx, req.(*EditCompanyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SheketService_AddEmployee_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddEmployeeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SheketServiceServer).AddEmployee(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sheketproto.SheketService/AddEmployee",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SheketServiceServer).AddEmployee(ctx, req.(*AddEmployeeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SheketService_SyncEntity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EntityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SheketServiceServer).SyncEntity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sheketproto.SheketService/SyncEntity",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SheketServiceServer).SyncEntity(ctx, req.(*EntityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SheketService_SyncTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SheketServiceServer).SyncTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sheketproto.SheketService/SyncTransaction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SheketServiceServer).SyncTransaction(ctx, req.(*TransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SheketService_IssuePayment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IssuePaymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SheketServiceServer).IssuePayment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sheketproto.SheketService/IssuePayment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SheketServiceServer).IssuePayment(ctx, req.(*IssuePaymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SheketService_VerifyPayment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyPaymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SheketServiceServer).VerifyPayment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sheketproto.SheketService/VerifyPayment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SheketServiceServer).VerifyPayment(ctx, req.(*VerifyPaymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _SheketService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "sheketproto.SheketService",
	HandlerType: (*SheketServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UserSignup",
			Handler:    _SheketService_UserSignup_Handler,
		},
		{
			MethodName: "SyncCompanies",
			Handler:    _SheketService_SyncCompanies_Handler,
		},
		{
			MethodName: "EditUserName",
			Handler:    _SheketService_EditUserName_Handler,
		},
		{
			MethodName: "CreateCompany",
			Handler:    _SheketService_CreateCompany_Handler,
		},
		{
			MethodName: "EditCompany",
			Handler:    _SheketService_EditCompany_Handler,
		},
		{
			MethodName: "AddEmployee",
			Handler:    _SheketService_AddEmployee_Handler,
		},
		{
			MethodName: "SyncEntity",
			Handler:    _SheketService_SyncEntity_Handler,
		},
		{
			MethodName: "SyncTransaction",
			Handler:    _SheketService_SyncTransaction_Handler,
		},
		{
			MethodName: "IssuePayment",
			Handler:    _SheketService_IssuePayment_Handler,
		},
		{
			MethodName: "VerifyPayment",
			Handler:    _SheketService_VerifyPayment_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: fileDescriptor0,
}

func init() { proto.RegisterFile("sheket_service.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 2312 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xac, 0x59, 0x4b, 0x6f, 0x23, 0x59,
	0x15, 0xa6, 0xec, 0xd8, 0xb1, 0x8f, 0x1f, 0x49, 0x2a, 0xce, 0x24, 0xe3, 0xd6, 0x4c, 0xa7, 0x6b,
	0xa6, 0x5b, 0xad, 0x66, 0x70, 0x0f, 0x8d, 0x46, 0x30, 0x80, 0x46, 0xca, 0xc3, 0xad, 0xf1, 0x28,
	0x9d, 0x0e, 0x95, 0xa4, 0x41, 0x3c, 0x64, 0xb9, 0xed, 0x4a, 0x52, 0x8a, 0x5d, 0xe5, 0x71, 0x95,
	0xd3, 0xf2, 0x02, 0x58, 0x01, 0x1b, 0x36, 0x6c, 0x60, 0x09, 0x48, 0x2c, 0x90, 0x58, 0xf1, 0x13,
	0xf8, 0x05, 0xfc, 0x01, 0x36, 0xfc, 0x93, 0x39, 0xf7, 0xdc, 0x87, 0x6f, 0x3d, 0xec, 0x38, 0xed,
	0x5e, 0xb9, 0xea, 0xf8, 0xbb, 0xe7, 0x7e, 0xe7, 0xdc, 0xf3, 0xb8, 0xb7, 0x2e, 0xd4, 0x82, 0x2b,
	0xe7, 0xda, 0x09, 0xdb, 0x81, 0x33, 0xba, 0x71, 0xbb, 0x4e, 0x63, 0x38, 0xf2, 0x43, 0xdf, 0x2c,
	0x71, 0x29, 0xbd, 0x58, 0x55, 0x28, 0x37, 0x07, 0xc3, 0x70, 0x62, 0x3b, 0x5f, 0x8f, 0x9d, 0x20,
	0xb4, 0xd6, 0xa0, 0x22, 0xde, 0x83, 0xa1, 0xef, 0x05, 0x8e, 0xf5, 0x14, 0xe0, 0x94, 0xf0, 0x7b,
	0xe3, 0xf0, 0xca, 0x7c, 0x00, 0xe5, 0xbe, 0x7f, 0xe9, 0x7a, 0xed, 0xae, 0xef, 0x5f, 0xbb, 0xce,
	0x8e, 0xb1, 0x6b, 0x3c, 0x2e, 0xda, 0x25, 0x92, 0x1d, 0x90, 0xc8, 0x7a, 0x02, 0xc5, 0x03, 0x7f,
	0x30, 0xec, 0x78, 0x93, 0xd6, 0xa1, 0xf9, 0x01, 0x40, 0x97, 0xbf, 0xb4, 0xdd, 0x1e, 0xa1, 0x73,
	0x76, 0x51, 0x48, 0x5a, 0x3d, 0xeb, 0xd7, 0x50, 0x12, 0x58, 0xd2, 0xfe, 0x7d, 0x80, 0x40, 0xcd,
	0x45, 0xe8, 0xd2, 0xb3, 0xed, 0x86, 0x46, 0xb7, 0x31, 0xa5, 0x62, 0x6b, 0x50, 0xf3, 0xb3, 0xc8,
	0x34, 0x19, 0x1a, 0xf8, 0x5e, 0x64, 0xa0, 0xa2, 0xa4, 0x4f, 0xff, 0x10, 0x2a, 0xa7, 0xae, 0x77,
	0x39, 0x1e, 0x0a, 0xeb, 0xcd, 0x1a, 0xe4, 0x42, 0xff, 0xda, 0xf1, 0x84, 0x5d, 0xfc, 0xc5, 0xba,
	0x82, 0xea, 0xa9, 0x7b, 0xe9, 0x31, 0x18, 0x77, 0x8a, 0x59, 0x87, 0xc2, 0x18, 0x9d, 0xea, 0x75,
	0x06, 0xd2, 0x05, 0xea, 0xdd, 0xdc, 0x86, 0x55, 0xf6, 0x2c, 0x89, 0xe4, 0xec, 0x3c, 0x7b, 0x6d,
	0xf5, 0x12, 0xbe, 0xcb, 0x26, 0x7d, 0xf7, 0x77, 0x03, 0xcc, 0xd3, 0x89, 0xd7, 0x15, 0x6c, 0x25,
	0xad, 0x6f, 0xc3, 0x4a, 0x67, 0x01, 0x8f, 0x10, 0xc8, 0x7c, 0x9f, 0x73, 0x6b, 0x8f, 0x9c, 0x1b,
	0x41, 0x80, 0xf8, 0xd8, 0xce, 0x8d, 0x79, 0x0f, 0x8a, 0x3d, 0x87, 0x45, 0x02, 0x23, 0xc7, 0xa7,
	0x2f, 0x70, 0x01, 0xd2, 0x7b, 0x04, 0x6b, 0x7d, 0xbf, 0xdb, 0xe9, 0xb7, 0x69, 0x74, 0xe8, 0xa2,
	0x69, 0x2b, 0x04, 0xa9, 0x90, 0xf8, 0x1c, 0xa5, 0x67, 0x28, 0xb4, 0xfe, 0x69, 0xc0, 0xc6, 0xb1,
	0xf3, 0x66, 0x19, 0x8a, 0xe8, 0x09, 0xb9, 0x5c, 0xe4, 0xc2, 0x0c, 0xf7, 0x84, 0x90, 0x1d, 0x33,
	0x2f, 0xbe, 0x13, 0xaa, 0xff, 0x36, 0x60, 0x55, 0xf0, 0xbc, 0x25, 0x12, 0x17, 0xa1, 0xf4, 0x21,
	0xc0, 0xd0, 0x19, 0x0d, 0xdc, 0x20, 0x70, 0x7d, 0x4f, 0x70, 0xd2, 0x24, 0xe6, 0x43, 0xa8, 0x06,
	0x18, 0x26, 0x4e, 0xaf, 0xdd, 0x47, 0x9a, 0x18, 0x26, 0x92, 0x14, 0x97, 0x1e, 0x71, 0x21, 0x23,
	0x32, 0xec, 0x4c, 0x06, 0x8e, 0x17, 0x32, 0x22, 0x39, 0x82, 0x14, 0x85, 0x04, 0x63, 0x72, 0x4f,
	0xa5, 0xc4, 0x91, 0x8b, 0x7e, 0x7d, 0x06, 0x82, 0xa4, 0xeb, 0x04, 0xc8, 0x3a, 0x8b, 0xce, 0xad,
	0xa5, 0x05, 0xb6, 0x3d, 0x85, 0x59, 0xbf, 0x82, 0xcd, 0x66, 0xcf, 0x0d, 0x99, 0x1b, 0x18, 0xf1,
	0xb7, 0x8d, 0x22, 0xcf, 0x79, 0xa3, 0xfb, 0x62, 0x15, 0xdf, 0x99, 0x3a, 0xeb, 0x4f, 0x18, 0xa4,
	0x7b, 0xbd, 0x1e, 0x96, 0x89, 0xbe, 0x3f, 0x71, 0x94, 0xfa, 0x1f, 0x82, 0xf4, 0x96, 0x96, 0xbd,
	0x3b, 0x69, 0x5c, 0x69, 0x1a, 0x1d, 0x6c, 0xde, 0x87, 0x92, 0x23, 0xd4, 0x4d, 0xf3, 0x06, 0xa4,
	0x08, 0x97, 0xe7, 0x16, 0xdf, 0x5b, 0xbf, 0x80, 0xcd, 0x08, 0x25, 0x91, 0xa7, 0x31, 0xbd, 0x46,
	0x42, 0xef, 0x47, 0x50, 0x51, 0x00, 0xcd, 0xd6, 0xb2, 0x14, 0x92, 0xc1, 0x7f, 0xcb, 0xc0, 0x66,
	0x2b, 0x08, 0xc6, 0xce, 0x09, 0x5f, 0x25, 0x69, 0xf1, 0x5b, 0x97, 0xab, 0x0f, 0x12, 0xe5, 0x2a,
	0x12, 0x8b, 0x48, 0xaa, 0xeb, 0x7b, 0xe1, 0xa8, 0xd3, 0x0d, 0xdb, 0xe1, 0x64, 0xc8, 0x2b, 0x45,
	0xce, 0x2e, 0x4b, 0xe1, 0x19, 0xca, 0x18, 0xa8, 0x37, 0x1e, 0x75, 0x42, 0xb4, 0xbe, 0xdd, 0xeb,
	0x4c, 0x02, 0x0a, 0x36, 0x04, 0x49, 0xe1, 0x21, 0xca, 0x58, 0x48, 0x2a, 0xf3, 0xfa, 0xee, 0xc0,
	0x0d, 0x29, 0xde, 0x36, 0x6c, 0x65, 0xf4, 0x11, 0x13, 0xb2, 0xe0, 0x7f, 0x3d, 0xea, 0x78, 0xdd,
	0x2b, 0x01, 0xca, 0x13, 0xa8, 0xc4, 0x65, 0x1c, 0x82, 0x94, 0xdd, 0xd0, 0x19, 0x08, 0xc0, 0x2a,
	0x01, 0x8a, 0x4c, 0x42, 0x7f, 0x5b, 0x01, 0xd4, 0xa2, 0x1e, 0x12, 0x0b, 0xf0, 0x04, 0x36, 0x5c,
	0x26, 0xef, 0xb5, 0x13, 0xc9, 0xb7, 0xc6, 0xff, 0x38, 0x50, 0x66, 0x3f, 0x85, 0x4d, 0x99, 0x18,
	0x3d, 0x27, 0xe8, 0x8e, 0xdc, 0x21, 0xb3, 0x43, 0xac, 0x88, 0x29, 0xfe, 0x3a, 0x9c, 0xfe, 0x63,
	0xfd, 0xc5, 0x80, 0xda, 0x2b, 0x67, 0xe4, 0x5e, 0x4c, 0x62, 0x0b, 0xb3, 0x4c, 0x28, 0x46, 0x0a,
	0x4f, 0xe6, 0xf6, 0xc2, 0x93, 0x4d, 0x2b, 0x3c, 0x5f, 0xc0, 0x56, 0x8c, 0x98, 0xf0, 0x47, 0xb2,
	0x46, 0x18, 0x29, 0x35, 0xc2, 0xba, 0x06, 0x93, 0x65, 0x70, 0xac, 0xc6, 0x2e, 0x63, 0xd6, 0x9c,
	0x7c, 0xfe, 0x4f, 0x06, 0x56, 0x5a, 0xb8, 0x92, 0xac, 0x73, 0xd1, 0x1a, 0x8b, 0x25, 0xda, 0xb0,
	0xf3, 0xec, 0x15, 0xcd, 0x36, 0x61, 0x45, 0x1b, 0x48, 0xcf, 0x4c, 0xd6, 0xf5, 0x7b, 0xd2, 0x7e,
	0x7a, 0x66, 0xb2, 0xf3, 0xf3, 0xd6, 0xa1, 0xa8, 0x7b, 0x2b, 0x63, 0x7c, 0x66, 0x29, 0x18, 0x84,
	0x9d, 0x70, 0x1c, 0xb4, 0x2f, 0xfa, 0x9d, 0x4b, 0x8a, 0x3f, 0x4c, 0x41, 0x2e, 0x7a, 0x8e, 0x12,
	0x06, 0xe8, 0x76, 0x42, 0xe7, 0xd2, 0x1f, 0x51, 0x70, 0xf0, 0xd8, 0x03, 0x29, 0xc2, 0xd9, 0x1b,
	0xb0, 0x39, 0xf6, 0xdc, 0xb0, 0xed, 0x5f, 0xb4, 0x07, 0x4e, 0x27, 0x18, 0x8f, 0x1c, 0xe6, 0x52,
	0x8a, 0xc1, 0x9c, 0xbd, 0xc1, 0xfe, 0x7a, 0x79, 0xf1, 0x62, 0xfa, 0x87, 0xf9, 0x18, 0xd6, 0xaf,
	0x3a, 0x01, 0xc6, 0xd0, 0xc8, 0xbd, 0x41, 0x47, 0x33, 0xc0, 0x4e, 0x01, 0xc1, 0x05, 0xbb, 0x8a,
	0xf2, 0x43, 0x2e, 0x3e, 0xf7, 0x78, 0xdc, 0x4b, 0x14, 0xd9, 0x57, 0xe4, 0x45, 0x5f, 0xc8, 0xa8,
	0xe8, 0xe3, 0x82, 0x49, 0xc8, 0x05, 0xa6, 0x9e, 0x3f, 0xda, 0x01, 0x04, 0x19, 0x76, 0x45, 0x48,
	0x9f, 0x93, 0x90, 0xd5, 0xc4, 0xc2, 0x81, 0xa0, 0x1c, 0xb7, 0xc8, 0x48, 0x58, 0x94, 0xe6, 0x4f,
	0x8c, 0xbb, 0x61, 0x67, 0x24, 0xba, 0x42, 0x96, 0x86, 0x14, 0xb8, 0x80, 0x0f, 0xb8, 0xb3, 0x63,
	0x2d, 0x0f, 0xf2, 0xfb, 0x94, 0xc1, 0x4c, 0xb7, 0xc8, 0x6f, 0x45, 0xa7, 0xc0, 0x05, 0xb3, 0x17,
	0x97, 0xe6, 0xcb, 0xce, 0x9e, 0x6f, 0x25, 0x31, 0x5f, 0x1b, 0x0a, 0xb2, 0x00, 0xdf, 0x5e, 0x78,
	0xd3, 0x66, 0xbd, 0xad, 0xc8, 0xff, 0xce, 0x00, 0xe0, 0x16, 0x51, 0xb8, 0xce, 0xb5, 0x4a, 0x8b,
	0xe5, 0x4c, 0x24, 0x96, 0x71, 0xeb, 0xf6, 0xf5, 0xb8, 0xe3, 0x85, 0x6e, 0x38, 0xa1, 0x29, 0x0c,
	0x5b, 0xbd, 0x53, 0x76, 0x5e, 0x39, 0xfd, 0x8b, 0x36, 0xcb, 0x66, 0x2a, 0x3e, 0xb2, 0x83, 0x33,
	0xe9, 0x91, 0x10, 0x5a, 0xc7, 0x50, 0xe5, 0x34, 0xd4, 0x8a, 0xcf, 0xa5, 0x12, 0x0b, 0x87, 0x4c,
	0x3c, 0x1c, 0xac, 0xff, 0x96, 0x71, 0xd3, 0x4d, 0x0c, 0x64, 0xa6, 0xff, 0x18, 0x72, 0x8c, 0xae,
	0xec, 0xf8, 0x8f, 0x22, 0x39, 0x1e, 0x81, 0x36, 0xc4, 0x2f, 0xf3, 0x88, 0xcd, 0x07, 0x99, 0x5f,
	0x81, 0xd4, 0xce, 0x36, 0x0d, 0x19, 0x52, 0xf1, 0xe4, 0x76, 0x15, 0xd2, 0x1a, 0x5b, 0x1b, 0x6d,
	0x1e, 0x82, 0x30, 0x04, 0x35, 0x65, 0x49, 0xd3, 0xe3, 0xdb, 0x35, 0x71, 0xef, 0xd8, 0x6a, 0xa4,
	0xf9, 0x25, 0x14, 0xe5, 0xda, 0xb3, 0x46, 0xb5, 0x20, 0x21, 0xd5, 0xce, 0xa7, 0x83, 0xcd, 0x63,
	0x10, 0x6d, 0xa9, 0x45, 0xfe, 0xc9, 0x91, 0xae, 0x4f, 0x16, 0xa5, 0x44, 0x5e, 0xd2, 0x15, 0x98,
	0xbf, 0x84, 0xf5, 0xd7, 0xfa, 0x5a, 0x32, 0x8f, 0xe5, 0x49, 0xe9, 0xa7, 0x8b, 0x2a, 0x55, 0x7e,
	0x4b, 0x68, 0x8a, 0x57, 0xec, 0xda, 0x5d, 0x2a, 0x36, 0x96, 0x31, 0xbf, 0x8f, 0x7d, 0x53, 0x86,
	0x0e, 0xdb, 0xcf, 0x6f, 0x51, 0x1e, 0x55, 0x51, 0xae, 0x26, 0xc5, 0x6d, 0xfd, 0x2e, 0x94, 0x19,
	0x92, 0xe2, 0x9d, 0xa1, 0xde, 0xe3, 0xd9, 0x86, 0x32, 0xb2, 0x17, 0x11, 0x1f, 0x03, 0x1b, 0xd3,
	0x16, 0x31, 0xca, 0x30, 0xdb, 0x7c, 0xb7, 0x80, 0x52, 0xb1, 0x58, 0x88, 0xfa, 0x0e, 0x6c, 0x6a,
	0x28, 0xa5, 0x6e, 0x87, 0xa0, 0xeb, 0x0a, 0x1a, 0x53, 0x3a, 0x70, 0x06, 0xaf, 0xc5, 0x71, 0xe3,
	0x7d, 0xa5, 0xf4, 0x05, 0x09, 0x19, 0xea, 0x33, 0xd8, 0xd6, 0x94, 0x46, 0xac, 0xa9, 0x13, 0xbc,
	0xa6, 0x14, 0x6b, 0x36, 0xd5, 0x7d, 0x28, 0x69, 0x91, 0x8d, 0x99, 0xb9, 0xc2, 0xf8, 0x88, 0x9e,
	0xb7, 0x11, 0xf1, 0x20, 0xf1, 0xa1, 0xbf, 0xcd, 0xcf, 0x21, 0x8f, 0xf5, 0x58, 0xee, 0x1a, 0xaa,
	0xcf, 0x1e, 0xcc, 0x59, 0xc3, 0x3d, 0x02, 0xda, 0x62, 0x40, 0xfd, 0xb7, 0xb0, 0x16, 0xcb, 0x03,
	0xf3, 0xbb, 0x50, 0x90, 0x7c, 0xc5, 0xc4, 0x5b, 0xd1, 0xa5, 0x93, 0x7c, 0x15, 0x6c, 0x19, 0x02,
	0x6f, 0xa0, 0x12, 0x09, 0x2b, 0xdc, 0xaf, 0xe7, 0xb9, 0xd7, 0xc4, 0xe4, 0x9b, 0x11, 0x5d, 0x62,
	0xd9, 0x04, 0xe4, 0xdd, 0x58, 0xae, 0xca, 0xf7, 0x54, 0x9b, 0x71, 0x47, 0x6d, 0xcc, 0x69, 0x32,
	0x5b, 0xc5, 0x41, 0x3c, 0xea, 0x34, 0x95, 0xd4, 0x0a, 0x56, 0xff, 0x03, 0x9e, 0x28, 0x13, 0x69,
	0xba, 0x0c, 0x07, 0xdc, 0x98, 0x4f, 0x73, 0x5c, 0xb0, 0xd8, 0x4e, 0xf1, 0x1e, 0x45, 0x8e, 0x06,
	0xad, 0xe3, 0x8e, 0x72, 0x2b, 0x35, 0xb7, 0x97, 0x61, 0x73, 0x00, 0xd5, 0x48, 0x61, 0x98, 0x08,
	0x46, 0xf7, 0x52, 0x18, 0xa9, 0x90, 0x8a, 0x0d, 0xb1, 0x3e, 0x81, 0x3c, 0x57, 0x6b, 0x02, 0xe4,
	0x0f, 0xec, 0xe6, 0xde, 0x59, 0x73, 0xfd, 0x5b, 0xec, 0xf9, 0xfc, 0xe4, 0x90, 0x3d, 0x1b, 0xec,
	0xf9, 0xb0, 0x79, 0xd4, 0xc4, 0xe7, 0x8c, 0xf5, 0xbf, 0x32, 0x54, 0x25, 0x27, 0xb1, 0xf3, 0x7c,
	0x09, 0xeb, 0xe3, 0x61, 0x0f, 0xd5, 0x89, 0x42, 0xe1, 0xf6, 0x64, 0x77, 0x79, 0x98, 0x6a, 0x0a,
	0x1f, 0xd6, 0x38, 0xe7, 0x63, 0x5a, 0x3d, 0xbb, 0x2a, 0x86, 0xb7, 0xa8, 0x8f, 0x06, 0xe6, 0x29,
	0x98, 0x52, 0xa1, 0xea, 0x7d, 0xb2, 0xdb, 0x2c, 0xa8, 0x52, 0x32, 0x12, 0xab, 0x81, 0x4a, 0x7f,
	0x0a, 0x35, 0xa9, 0x54, 0xeb, 0x99, 0xb2, 0xf5, 0x2c, 0xa8, 0x56, 0xf2, 0x3a, 0x50, 0x2d, 0x96,
	0x55, 0x62, 0xd1, 0x51, 0x79, 0xf7, 0xf9, 0x78, 0x9e, 0x26, 0xf6, 0x05, 0x46, 0xef, 0xa7, 0x5f,
	0x46, 0xfa, 0x69, 0x6e, 0x4e, 0x17, 0xd4, 0x14, 0xa4, 0x76, 0xd3, 0x7d, 0xad, 0x9b, 0xe6, 0xe7,
	0xb4, 0x76, 0x4d, 0x4f, 0xa2, 0x97, 0x3e, 0xd7, 0x7b, 0xe9, 0xea, 0x62, 0x64, 0xd2, 0x3a, 0xe9,
	0xcf, 0x53, 0x3a, 0x5f, 0x81, 0xd4, 0x35, 0x16, 0xe3, 0x34, 0xa7, 0xef, 0x61, 0xef, 0x62, 0xa7,
	0x8d, 0x48, 0xb5, 0xaf, 0xf1, 0xde, 0x85, 0xf2, 0x58, 0xef, 0x62, 0x48, 0xd5, 0x6c, 0x78, 0x87,
	0x03, 0x94, 0x69, 0x6d, 0x86, 0x21, 0xb4, 0xde, 0xc5, 0xfb, 0x1b, 0x1b, 0x17, 0xe9, 0x5d, 0x1a,
	0x4a, 0xa9, 0xe3, 0x6d, 0x6e, 0x5d, 0x41, 0x63, 0x4a, 0xb5, 0xde, 0xb5, 0xa3, 0x94, 0x46, 0x7a,
	0x97, 0xa6, 0x34, 0x62, 0x0d, 0x6f, 0x75, 0x35, 0xa5, 0x58, 0xef, 0x5d, 0x1e, 0x14, 0x64, 0x08,
	0x2d, 0xda, 0xb8, 0x7e, 0x04, 0x39, 0xb6, 0x93, 0x76, 0x44, 0xf5, 0x7e, 0x78, 0xdb, 0x0a, 0x9c,
	0x32, 0xb0, 0xcd, 0xc7, 0xd4, 0x7f, 0x03, 0x65, 0x3d, 0xe2, 0xde, 0xa6, 0x6f, 0x2d, 0x35, 0xff,
	0x0d, 0xc0, 0x34, 0x2a, 0xee, 0xd6, 0xb6, 0xde, 0x85, 0xdd, 0xaa, 0x6b, 0xe9, 0xad, 0xc7, 0x58,
	0xa8, 0xf5, 0x2c, 0x37, 0xff, 0x9f, 0xc5, 0xd7, 0xda, 0x58, 0xab, 0x48, 0xd6, 0x7b, 0xe3, 0xce,
	0xf5, 0x7e, 0x39, 0x62, 0x9f, 0x43, 0x51, 0x55, 0x43, 0x73, 0x0b, 0xf2, 0xb4, 0x3b, 0x94, 0x07,
	0x93, 0x1c, 0xdb, 0x17, 0x92, 0x98, 0x12, 0x4f, 0x7e, 0x7f, 0xca, 0xb1, 0x94, 0xeb, 0x59, 0x1f,
	0x41, 0x51, 0xa9, 0x33, 0x8b, 0x90, 0x6b, 0xfe, 0xac, 0x75, 0x7a, 0x86, 0x9d, 0xa6, 0x04, 0xab,
	0x76, 0xf3, 0xc5, 0xcb, 0x57, 0xcd, 0xc3, 0x75, 0xc3, 0xfa, 0x63, 0x16, 0x4a, 0x67, 0xc8, 0x37,
	0x10, 0x1d, 0xee, 0x18, 0xd6, 0xc3, 0xe9, 0x6b, 0x4b, 0x3b, 0xb9, 0x58, 0x11, 0xde, 0xda, 0x18,
	0xfe, 0x4c, 0x19, 0x90, 0x18, 0xcb, 0x3e, 0x56, 0x90, 0x4c, 0xb2, 0x33, 0xed, 0x55, 0x7a, 0x47,
	0xda, 0x91, 0x93, 0x56, 0x36, 0x76, 0xd2, 0x62, 0xdf, 0x6e, 0x90, 0xf7, 0xf4, 0x8b, 0x70, 0xd6,
	0x2e, 0x30, 0x01, 0xfb, 0x26, 0xc3, 0xbe, 0x60, 0x71, 0xa5, 0x9e, 0x8f, 0x6e, 0x15, 0xdf, 0x5d,
	0x49, 0x72, 0x8c, 0x02, 0x75, 0xe4, 0xcd, 0x4f, 0x8f, 0xbc, 0xf5, 0x7f, 0x18, 0x50, 0x54, 0x3c,
	0xe3, 0x47, 0xca, 0x9c, 0x3a, 0x52, 0x2a, 0xcd, 0xf4, 0xb1, 0x4e, 0x7c, 0x5a, 0x26, 0x09, 0x7d,
	0xa9, 0x9b, 0x77, 0xe2, 0x7c, 0x04, 0x6b, 0x7e, 0x78, 0x85, 0x25, 0x68, 0x6a, 0x14, 0x3f, 0x58,
	0x57, 0x48, 0xbc, 0xaf, 0x59, 0x46, 0x73, 0x6b, 0xdc, 0x0b, 0x4c, 0xc0, 0xa8, 0x5b, 0xff, 0xc7,
	0x38, 0xd4, 0x5c, 0x3b, 0x3d, 0x44, 0x96, 0x35, 0xcf, 0xca, 0x15, 0xd9, 0x99, 0xb5, 0x22, 0x76,
	0x04, 0x1d, 0x3f, 0xba, 0x64, 0xee, 0x72, 0x74, 0x99, 0x71, 0x90, 0xc8, 0xd2, 0x8a, 0x24, 0x0f,
	0x12, 0x16, 0x54, 0x18, 0x9c, 0xfb, 0x90, 0x01, 0xf9, 0xd2, 0x95, 0x50, 0x48, 0xfc, 0x10, 0x63,
	0xfd, 0x2b, 0x07, 0x9b, 0x11, 0x1b, 0xc5, 0xb6, 0xe6, 0x2c, 0xd5, 0xc8, 0x4f, 0x67, 0x1a, 0xa9,
	0xe7, 0xcc, 0x6c, 0xe3, 0x7f, 0x12, 0x3d, 0x65, 0xf2, 0x4d, 0xcd, 0xd3, 0x85, 0x94, 0xce, 0x3a,
	0x68, 0x5e, 0xc2, 0xb6, 0xdc, 0xd9, 0x68, 0x53, 0x69, 0x9b, 0x9b, 0xdb, 0xd5, 0x8b, 0x9c, 0xe6,
	0x11, 0xd9, 0xb3, 0xb7, 0xc6, 0xda, 0xbb, 0x48, 0x1f, 0xdc, 0xe9, 0xcc, 0xe8, 0x84, 0xdc, 0xa7,
	0xc9, 0x4e, 0x88, 0xce, 0x67, 0xf0, 0xa9, 0xf3, 0x73, 0xdc, 0xf9, 0x28, 0x94, 0xce, 0xaf, 0x5f,
	0xc0, 0x5a, 0xcc, 0x5f, 0x2c, 0x3c, 0x34, 0x33, 0x52, 0xbf, 0x45, 0xea, 0x26, 0xe8, 0xe0, 0x99,
	0x37, 0x64, 0xf5, 0xdf, 0x1b, 0x50, 0x8d, 0xfa, 0x30, 0xb6, 0x95, 0x37, 0x16, 0xde, 0xca, 0x2f,
	0x57, 0x40, 0xbf, 0x80, 0x6a, 0xd4, 0xd9, 0xb1, 0x2a, 0x6a, 0xa6, 0x57, 0xd1, 0xac, 0xa8, 0xa2,
	0xcf, 0xfe, 0x9a, 0x87, 0x0a, 0xff, 0xf6, 0x7f, 0xca, 0xaf, 0x5e, 0xcd, 0x26, 0x00, 0xfb, 0x3a,
	0xcc, 0xef, 0x11, 0xcd, 0x7a, 0xf4, 0x96, 0x40, 0xbf, 0x83, 0xac, 0xdf, 0x8b, 0xfd, 0x17, 0xb9,
	0x78, 0xfc, 0x0a, 0xf5, 0xaa, 0xfb, 0x41, 0xb6, 0xd3, 0xba, 0x1f, 0x45, 0x27, 0xee, 0x0e, 0xeb,
	0xa9, 0x29, 0x4b, 0x57, 0x4b, 0x47, 0x50, 0xd6, 0xaf, 0x89, 0xcc, 0xdd, 0xa8, 0x8b, 0x92, 0x37,
	0x48, 0xf5, 0x7a, 0xbc, 0x9d, 0x6a, 0xe7, 0x8b, 0x26, 0x54, 0x0e, 0x46, 0x0e, 0xba, 0x4c, 0x5e,
	0xb8, 0x7d, 0x18, 0x01, 0x27, 0x6e, 0x0c, 0xeb, 0xa9, 0xd7, 0x58, 0x68, 0x60, 0x49, 0xfb, 0xf2,
	0x1d, 0x33, 0x2f, 0xf9, 0x4d, 0x7c, 0x2e, 0xa5, 0x13, 0x28, 0x69, 0x97, 0x42, 0x31, 0x5d, 0xc9,
	0x1b, 0xac, 0xfa, 0xee, 0x6c, 0x80, 0x32, 0x92, 0x76, 0x3a, 0x3c, 0x7c, 0x62, 0xab, 0x18, 0x39,
	0x03, 0xc6, 0x56, 0x31, 0x76, 0x16, 0x3b, 0x4b, 0xe6, 0xd3, 0xfd, 0xd9, 0xd9, 0x9f, 0x46, 0x2e,
	0xad, 0x14, 0x9e, 0x42, 0x59, 0xbf, 0x83, 0x89, 0xad, 0x67, 0xca, 0x05, 0x56, 0xfd, 0xc1, 0x1c,
	0x84, 0x50, 0xfa, 0x0a, 0x2a, 0x91, 0x9b, 0x0c, 0x33, 0x3a, 0x26, 0xed, 0xfa, 0xa5, 0x6e, 0xcd,
	0x83, 0x70, 0xbd, 0xfb, 0x3f, 0x80, 0x5d, 0xec, 0x18, 0x8d, 0xc1, 0xf8, 0xda, 0x19, 0x75, 0x04,
	0xbe, 0xd1, 0xed, 0xbb, 0x88, 0x69, 0x78, 0x4e, 0xf8, 0xc6, 0x1f, 0x5d, 0xef, 0x9b, 0x91, 0x14,
	0x3a, 0x61, 0xda, 0x4e, 0x8c, 0xd7, 0x79, 0x52, 0xfb, 0xbd, 0x6f, 0x02, 0x00, 0x00, 0xff, 0xff,
	0xce, 0x94, 0xf5, 0xcd, 0xdd, 0x20, 0x00, 0x00,
}
